install:
  - curl -s https://static.rust-lang.org/rustup.sh | sudo sh - 
  - export LD_LIBRARY_PATH=/usr/local/lib
script:
  - cargo build
  - cargo test
notifications:
  email:
    on_success: never

